language: python
python:
  - "2.7"
#  - "2.6" # fails because of discover
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip install scripttest
# command to run tests, e.g. python setup.py test
#script:  
    #- python Command_line_Tests/fake_test.py 
    #- python -m unittest discover