language: python
python:
  - "2.7"
#  - "2.6" # fails because of discover
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
    - echo $DISPLAY
    - export DISPLAY=unix:0.0
    - echo $DISPLAY
    - sudo apt-get install python-scipy python-tk python-matplotlib
virtualenv:
    system_site_packages: true
install: 
    - pip install scripttest
#    - pip install python-tk # error
#    - pip install tkinter # causes an error
# command to run tests, e.g. python setup.py test
script:  
    - python Command_line_Tests/fake_test.py 
    - python Command_line_Tests/Rename_me.py -r angle
    #- python -m unittest discover